x = input("What would you like your first number to be: ")
y = input("What would you like your second number to be: ")
print("X is less than Y ", int(x) < int(y))
print("Y is less than X ", int(y) < int(x))
print("X is more than Y ", int(x) > int(y))
print("Y is more than X ", int(y) > int(x))
print("X is less or equal to Y ", int(x) <= int(y))
print("Y is less or equal to X ", int(y) <= int(x))
print("X is more or equal to Y ", int(x) >= int(y))
print("Y is more or equal to X ", int(y) >= int(x))
print("X is equal to Y ", int(x) == int(y))
print("Y is equal to X ", int(y) == int(x))
print("X is not equal to Y ", int(x) != int(y))
print("Y is not equal to X ", int(x) != int(y))