yours = input("enter your name ")
dads = input("enter your dads name ")
moms = input("enter your moms name ")
hobby1 = input("whats your first hobby? ")
hobby2 = input("whats your second hobby? ")
hobby3 = input("whats your third hobby? ")
hobby4 = input("whats your fourth hobby? ")
color = input("whats your favorite color? ")
car = input("whats your favorite car? ")
print("users name is " + yours + " " + "their dads name is " + moms + " " + dads + "Four hobbys are " + hobby1 + " " + hobby2 + " " + hobby3 + " " + hobby4 + " " + "and favorite car and color is " + color + " " + car)